package com.zltel.broadcast.lesson.dao;

import com.zltel.broadcast.common.support.BaseDao;
import com.zltel.broadcast.lesson.bean.LessonUnitRegistration;

public interface LessonUnitRegistrationMapper extends BaseDao<LessonUnitRegistration> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    int insert(LessonUnitRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    int insertSelective(LessonUnitRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    LessonUnitRegistration selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LessonUnitRegistration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lesson_unit_registration
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LessonUnitRegistration record);
}